resources:
- name: trying-git
  type: git
  source:
    uri: https://github.com/concourse/docs
    branch: main 
jobs:
- name: job-hello-world
  public: true  
  plan: 
  - get: trying-git
    trigger: true
  - task: hello-world
    file: my-concourse/tasks/hello_hema_task.yml
