resources:
- name: trying-git
  type: git
  icon: github
  source:
    uri: https://github.com/gumshuda404/my-concourse.git
    branch: test1
-  name: container-resource
   type: time
   source:
    interval: 10m

jobs:
- name: job-hello-hema
  plan: 
  - get: trying-git
    trigger: true
  - get: container-resource
    trigger: true
  - task: hello-hema
    config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ubuntu
            check_every: never
          inputs:
          - name: trying-git
          run:
            path: /bin/sh
            args: 
            - -c
            - |
              ls
              apt-get update -y
              apt-get install -y \
              apt-transport-https \
              ca-certificates \
              curl \
              software-properties-common

              curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
              apt-key fingerprint 0EBFCD88
              add-apt-repository \
              "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) \
              stable"
              apt-get update -y
              apt-get install -y docker-ce
              usermod -aG docker $USER
              docker --version
              pwd

              wget https://concourse-ci.org/docker-compose.yml
              ls
              docker-compose up -d
              #curl 'http://localhost:8080/api/v1/cli?arch=amd64&platform=linux' -o fly
              #sudo chmod +x ./fly 
              #sudo mv ./fly /usr/local/bin/
              #fly --version
              
              
