resources:
- name: trying-git
  type: git
  icon: github
  source:
    uri: https://github.com/gumshuda404/my-concourse.git
    branch: test1
-  name: container-resource
   type: time
   source:
    interval: 10m

jobs:
- name: job-hello-hema
  plan: 
  - get: trying-git
    trigger: true
  - get: container-resource
    trigger: true
  - task: hello-hema
    config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: gitea/gitea
            check_every: never
          inputs:
          - name: trying-git
          run:
            path: /bin/sh
            args: 
            - -c
            - |
              ls
              cd trying-git/
              ls
              git branch | cut -c 3- 
              cat README.md
