resources:
- name: trying-git
  type: git
  icon: github
  source:
    uri: https://github.com/gumshuda404/my-concourse.git
    branch: test1
-  name: container-resource
   type: time
   source:
    interval: 10m

jobs:
- name: job-hello-hema
  plan: 
  - get: trying-git
    trigger: true
  - get: container-resource
    trigger: true
  - task: hello-hema
    config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: gitea/gitea
            check_every: never
          inputs:
          - name: trying-git
          run:
            path: /bin/sh
            args: 
            - -c
            - |
              ls
              apt update
              docker --version 
              pwd
              wget https://concourse-ci.org/docker-compose.yml
              ls
              docker-compose up -d
              #curl 'http://localhost:8080/api/v1/cli?arch=amd64&platform=linux' -o fly
              #sudo chmod +x ./fly 
              #sudo mv ./fly /usr/local/bin/
              #fly --version
              
              
