resources:
- name: trying-git
  type: git
  icon: github
  source:
    uri: https://github.com/gumshuda404/my-concourse.git
    branch: test1
-  name: container-resource
   type: time
   source:
    interval: 10m

jobs:
- name: job-hello-hema
  plan: 
  - get: trying-git
    trigger: true
  - get: container-resource
    trigger: true
  - task: hello-hema
    config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: ubuntu
            check_every: never
          inputs:
          - name: trying-git
          run:
            path: /bin/sh
            args: 
            - -c
            - |
              ls
              apt-get update
              apt-get -y install grep
              apt-get -y install git 
              git clone https://github.com/gumshuda404/my-concourse.git
              cd my-concourse/
              git checkout test1
              ls
              git branch | cut -c 3- >curr_branches.txt
              git add .
              git commit -m new 
              git push 
              cat curr_branches.txt
              Fgrep -v -f present_pipeline_branches.txt curr_branches.txt >no_pipeline_branches.txt

            



              
