resources:
- name: trying-git
  type: git
  icon: github
  source:
    uri: https://github.com/gumshuda404/my-concourse.git
    branch: main
    
jobs:
- name: job-hello-hema
  public: true  
  plan: 
  - get: trying-git
    trigger: true
  - task: hello-hema
    config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: gitea/gitea
            check_every: never
          input:
          - name: trying-git
          run:
            path: /bin/ash
            args: 
              - "-c"
              - |
              - cat README.md 
            
